import Head from 'next/head';

import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Customers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Welcome to Volt Car Hire</h1>
      <Link href={'/customers'}>
        <h2 className={styles.link}>Customers</h2>
      </Link>
    </div>
  );
}
